// <auto-generated />
namespace WebApiTodoApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initproject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initproject));
        
        string IMigrationMetadata.Id
        {
            get { return "201712270026182_init project"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
